### ISSUE TITLE
Update to latest upstream

### ISSUE THREAD

**Issue by jasonmp85** [petere/postgresql-common#1]
Upstream appears to be at 188 (181 stable, 184 for ubuntu); some of the enhancements and bugfixes look nice to have; what are your plans for or blockers against keeping this package up-to-date?

**Comment by petere** [comment]
Updated to 189.

I generally only update it when there are significant changes, since it's a bit of manual work.

**Comment by jasonmp85** [comment]
Yup; looking over the repo that's pretty clear… would be nice if the scripts were slightly more OS-independent, but so it goes…

That said, thanks for the work! I can't remember what failure caused me to open this issue, but I remember it being fixed as early as the 180s, so whatever it was it should be gone now.
